#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org


. /lib/functions.sh
. /lib/functions/network.sh

START=99

DNS=8.8.8.8:53
TUNNEL_PORT=5353
SS_REDIR_PID_FILE=/var/run/ss-redir.pid
SS_TUNNEL_PID_FILE=/var/run/ss-tunnel.pid
CONFIG_FILE=/etc/shadowsocks.json

start() {
    sleep 10
	service_start /usr/bin/ss-tunnel -c $CONFIG_FILE -l $TUNNEL_PORT -L $DNS -u -f $SS_TUNNEL_PID_FILE
    service_start /usr/bin/ss-redir -c $CONFIG_FILE -f $SS_REDIR_PID_FILE
    echo "程序已经启动"
}

stop() {
    service_stop /usr/bin/ss-redir
	service_stop /usr/bin/ss-tunnel
	echo "程序已经停止"
}
restart() {
    service_stop /usr/bin/ss-redir
	service_stop /usr/bin/ss-tunnel
	service_start /usr/bin/ss-tunnel -c $CONFIG_FILE -l $TUNNEL_PORT -L $DNS -u -f $SS_TUNNEL_PID_FILE
    service_start /usr/bin/ss-redir -c $CONFIG_FILE -f $SS_REDIR_PID_FILE
	echo "程序已重启"
}
